import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Plus } from 'lucide-react';

const faqs = [
  {
    question: "What is BrewPot?",
    answer: "BrewPot is a design studio focused on all design work that helps your product succeed — from high-level design strategy that solves your product challenges, to day-to-day product design support including UI, UX, websites, and branding."
  },
  {
    question: "How many people are on the BrewPot team?",
    answer: "BrewPot is a one-person studio run entirely by me, Yating Zhao. I am an experienced product and UX/UI designer with a proven track record of shipping 30+ software products across many industries and platforms."
  },
  {
    question: "How do we communicate during the project? Will I talk directly with the designer?",
    answer: "You will work one-on-one with me, Yating Zhao.\n\nWe will have 2–3 face-to-face design workshops each week. During these workshops, I will present complete design solutions, along with supporting research and the strategies behind the design, in response to your previous requests.\n\nOutside of workshops, I will communicate with you asynchronously and respond to all your messages and questions."
  },
  {
    question: "Is there a limit to what I can request?",
    answer: "Requests for design and product problem-solving are unlimited. Complex tasks may take up to one week, while simpler ones are completed quickly, usually within 24–48 hours. I work on multiple tasks in parallel, so no task queue is needed."
  },
  {
    question: "What types of design are supported?",
    answer: "My core focus is delivering high-quality, user-friendly app interface designs and solving product UX problems, even for complex products and scenarios such as banking, web3, logistics, and healthcare.\n\nI also help refine and improve websites so your customers and users can clearly understand your product or service and appreciate its value.\n\nIn addition, I provide light brand design support, including logos, brand guidelines, and social media assets."
  },
  {
    question: "Can I book if you are currently fully booked?",
    answer: "Yes. If I’m fully booked, you can reserve my next available slot and lock your preferred start date. Once secured, your spot is reserved exclusively for you and will not be offered to others."
  },
  {
    question: "Can you sign an NDA?",
    answer: "Yes, I can sign an NDA to protect your product and project confidentiality."
  },
  {
    question: "Do you also do development?",
    answer: "I deliver 1:1 design-matched code generated by top AI coding tools, powering design-to-code implementation for your product."
  },
  {
    question: "Where are you based?",
    answer: "I’m based in California, USA, and work with clients worldwide."
  },
  {
    question: "When are your working hours?",
    answer: "My schedule is flexible. I primarily work Monday through Friday, and I respond to messages at any time."
  },
  {
    question: "How do I pay?",
    answer: "Payments are primarily in USD. Upon confirming our collaboration, I will send a formal invoice via Mercury. You can complete payment through the invoice portal, and a payment receipt will be issued immediately after your payment is processed. Alternative currencies and methods can be discussed case-by-case."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="pt-16 pb-12 bg-[#0A0A0A] text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid md:grid-cols-12 gap-12">
          <div className="md:col-span-4">
            <h2 className="font-heading font-normal text-[42px] md:text-[52px] text-white mb-2 tracking-tight leading-tight">Frequently Asked<br />Questions</h2>
          </div>

          <div className="md:col-span-8">
            <div>
              {faqs.map((faq, index) => (
                <div key={index} className={index !== 0 ? "border-t border-white/10" : ""}>
                  <button
                    onClick={() => setOpenIndex(openIndex === index ? null : index)}
                    className="w-full flex justify-between items-start text-left py-5 group"
                  >
                    <span className="text-lg font-normal text-neutral-200 group-hover:text-white transition-colors pr-8">
                      {faq.question}
                    </span>
                    <Plus
                      className={`w-5 h-5 text-neutral-400 transform transition-transform duration-300 ${openIndex === index ? 'rotate-45' : ''}`}
                    />
                  </button>
                  <AnimatePresence>
                    {openIndex === index && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden"
                      >
                        <p className="text-neutral-400 pb-6 leading-relaxed whitespace-pre-line">
                          {faq.answer}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-12 text-center">
          <p className="text-neutral-500 text-[16px] font-sans">
            Have more questions? Reach out at <a href="mailto:yatzhao@brewpot.co" className="text-white font-medium hover:underline">yatzhao@brewpot.co</a> for a reply within 12 hours.
          </p>
        </div>
      </div>
    </section>
  );
}
