import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Plus } from 'lucide-react';

const faqs = [
  {
    question: "What is BrewPot?",
    answer: "BrewPot is a one-person design studio founded in 2024 by me, Yating Zhao. My mission is to make it easy for every team to access professional UI/UX design support in a highly flexible and seamless way."
  },
  {
    question: "How do we communicate during the project? Will I talk directly with the designer?",
    answer: "You work one-on-one with me, Yating Zhao. We rely heavily on face-to-face communication in 2–3 design workshops weekly. In these sessions, you can ask any questions, and I will present my full range of research findings, recommended strategies, and complete design solutions. \n\nBetween meetings, I conduct detailed research and respond promptly to all your messages and questions."
  },
  {
    question: "Is there a limit to what I can request?",
    answer: "Unlimited design and product problem-solving requests. I’ll complete all that fits my fixed weekly time commitment—quantity doesn’t matter."
  },
  {
    question: "What types of design are supported?",
    answer: "My core focus is delivering high-quality, user-friendly app interface designs and solving product UX problems, even for complex products and scenarios such as banking, web3, logistics, and healthcare.\n\nI also help refine and improve websites so your customers and users can clearly understand your product or service and appreciate its value.\n\nIn addition, I provide light brand design support, including logos, brand guidelines, and social media assets."
  },
  {
    question: "How do I pay?",
    answer: "Payments are primarily in USD. Upon confirming our collaboration, I will send a formal invoice via Mercury. You can complete payment through the invoice portal, and a payment receipt will be issued immediately after your payment is processed. Alternative currencies and methods can be discussed case-by-case."
  },
  {
    question: "Can I reserve a future slot if you're currently full?",
    answer: "Yes. You can secure a future start date by paying in advance."
  },
  {
    question: "Can you sign an NDA?",
    answer: "Yes, I can sign an NDA to protect your product and project confidentiality."
  },
  {
    question: "Do you also do development?",
    answer: "I deliver 1:1 design-matched code generated by top AI coding tools, powering design-to-code implementation for your product."
  },
  {
    question: "Where are you based?",
    answer: "I’m based in California, USA, and work with clients worldwide."
  },
  {
    question: "When do you work?",
    answer: "My schedule is highly flexible to support teams across different time zones. I respond promptly and set aside dedicated face-to-face time to help you with any questions you may have."
  }
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="pt-16 pb-12 bg-[#0A0A0A] text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid md:grid-cols-12 gap-12">
          <div className="md:col-span-4">
            <h2 className="font-heading font-normal text-[42px] md:text-[52px] text-white mb-2 tracking-tight leading-tight">Frequently Asked<br />Questions</h2>
          </div>

          <div className="md:col-span-8">
            <div className="space-y-4">
              {faqs.map((faq, index) => (
                <div key={index} className={`${index !== faqs.length - 1 ? 'border-b border-white/10' : ''} pb-2`}>
                  <button
                    onClick={() => setOpenIndex(openIndex === index ? null : index)}
                    className="w-full flex justify-between items-start text-left py-3 group"
                  >
                    <span className="text-lg font-normal text-neutral-200 group-hover:text-white transition-colors pr-8">
                      {faq.question}
                    </span>
                    <Plus
                      className={`w-5 h-5 text-neutral-400 transform transition-transform duration-300 ${openIndex === index ? 'rotate-45' : ''}`}
                    />
                  </button>
                  <AnimatePresence>
                    {openIndex === index && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                        className="overflow-hidden"
                      >
                        <p className="text-neutral-400 pt-1 pb-3 leading-relaxed whitespace-pre-line">
                          {faq.answer}
                        </p>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="mt-20 text-center">
          <p className="text-neutral-500 text-[16px] font-sans">
            Have more questions? Reach out at <a href="mailto:yatzhao@brewpot.co" className="text-white font-medium hover:underline">yatzhao@brewpot.co</a> for a reply within 12 hours.
          </p>
        </div>
      </div>
    </section>
  );
}
